import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Printer, ArrowLeft, Sparkles } from 'lucide-react';
import { DiscoveryState, DEFAULT_DISCOVERY_STATE, SEGMENT_CONFIG, INDUSTRY_CONFIG, USE_CASES } from '@/types/useCase';
import { calculateValueCards, formatCurrencyShort } from '@/lib/useCaseMapping';
import { ResidualInputs, DEFAULT_RESIDUAL_INPUTS } from '@/types/estimator';

export default function ExportReport() {
  const navigate = useNavigate();
  const [discovery, setDiscovery] = useState<DiscoveryState>(DEFAULT_DISCOVERY_STATE);
  const [inputs, setInputs] = useState<ResidualInputs>(DEFAULT_RESIDUAL_INPUTS);
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  useEffect(() => {
    const d = sessionStorage.getItem('discovery');
    const i = sessionStorage.getItem('residual_inputs');
    if (d) try { setDiscovery(JSON.parse(d)); } catch {}
    if (i) try { setInputs({ ...DEFAULT_RESIDUAL_INPUTS, ...JSON.parse(i) }); } catch {}
  }, []);

  const valueCards = calculateValueCards(discovery);
  const totalAnnualValue = valueCards.reduce((sum, c) => sum + c.estimatedLaborValueRecaptured, 0);
  const totalFTEs = valueCards.reduce((sum, c) => sum + c.estimatedFTESaved, 0);
  const totalHours = valueCards.reduce((sum, c) => sum + c.estimatedHoursSavedPerMonth, 0);
  const segConfig = discovery.segment ? SEGMENT_CONFIG[discovery.segment] : null;
  const indConfig = discovery.industry ? INDUSTRY_CONFIG[discovery.industry] : null;
  const selectedUseCases = USE_CASES.filter((uc) => discovery.selectedUseCaseIds.includes(uc.id));

  return (
    <div className="min-h-screen bg-gray-100">

      {/* Print toolbar — hidden when printing */}
      <div className="print:hidden sticky top-0 z-50 bg-white border-b border-gray-200 px-6 py-3 flex items-center justify-between">
        <Button variant="ghost" onClick={() => navigate('/estimator')} className="gap-2">
          <ArrowLeft className="h-4 w-4" />
          Back to Estimator
        </Button>
        <div className="flex items-center gap-3">
          <span className="text-sm text-gray-500">Ready to share with your customer</span>
          <Button onClick={() => window.print()} className="gap-2 bg-blue-600 hover:bg-blue-700 text-white">
            <Printer className="h-4 w-4" />
            Save as PDF
          </Button>
        </div>
      </div>

      {/* Printable Report */}
      <div className="max-w-[850px] mx-auto my-8 print:my-0 bg-white shadow-lg print:shadow-none">

        {/* Header */}
        <div className="px-12 pt-10 pb-8 border-b-2 border-blue-600">
          <div className="flex items-start justify-between">
            <div>
              <div className="flex items-center gap-2 mb-3">
                <Sparkles className="h-5 w-5 text-blue-600" />
                <span className="text-sm font-semibold text-blue-600 tracking-wide">Microsoft Azure AI</span>
              </div>
              <h1 className="text-3xl font-bold text-gray-900">AI Business Value Assessment</h1>
              <p className="text-sm text-gray-500 mt-1">Listen & Consult Stage — Confidential Working Document</p>
            </div>
            <div className="text-right">
              <p className="text-sm font-medium text-gray-700">{today}</p>
              <p className="text-xs text-gray-400 mt-1">Generated by Azure AI Business Value Estimator</p>
            </div>
          </div>
        </div>

        {/* Customer Profile */}
        <div className="px-12 py-8 border-b border-gray-200">
          <div className="flex items-center gap-2 mb-4">
            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-600 text-white text-xs font-bold">1</span>
            <h2 className="text-lg font-bold text-gray-900">Customer Profile</h2>
          </div>
          <div className="grid grid-cols-3 gap-6">
            <div>
              <p className="text-xs text-gray-400 uppercase tracking-wide mb-1">Segment</p>
              <p className="text-sm font-semibold text-gray-900">{segConfig ? `${segConfig.icon} ${segConfig.label}` : '—'}</p>
              <p className="text-xs text-gray-500">{segConfig?.subtitle}</p>
            </div>
            <div>
              <p className="text-xs text-gray-400 uppercase tracking-wide mb-1">Industry</p>
              <p className="text-sm font-semibold text-gray-900">{indConfig ? `${indConfig.icon} ${indConfig.label}` : '—'}</p>
            </div>
            <div>
              <p className="text-xs text-gray-400 uppercase tracking-wide mb-1">AI Maturity</p>
              <p className="text-sm font-semibold text-gray-900">{discovery.aiMaturity ?? '—'}</p>
              <p className="text-xs text-gray-500">
                {discovery.aiMaturity === 'early' && 'Pilots and proofs of concept'}
                {discovery.aiMaturity === 'scaling' && 'Multiple use cases in production'}
                {discovery.aiMaturity === 'mature' && 'AI integrated across workflows'}
              </p>
            </div>
          </div>
        </div>

        {/* Use Cases Selected */}
        <div className="px-12 py-8 border-b border-gray-200">
          <div className="flex items-center gap-2 mb-4">
            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-600 text-white text-xs font-bold">2</span>
            <h2 className="text-lg font-bold text-gray-900">AI Use Cases Identified</h2>
          </div>
          <div className="space-y-3">
            {selectedUseCases.map((uc) => (
              <div key={uc.id} className="flex items-center gap-3 p-3 rounded-lg border border-gray-100 bg-gray-50">
                <span className="text-xl">{uc.icon}</span>
                <div className="flex-1">
                  <p className="text-sm font-semibold text-gray-900">{uc.label}</p>
                  <p className="text-xs text-gray-500">{uc.hook}</p>
                </div>
                <span className="text-xs text-gray-400 bg-white px-2 py-1 rounded border border-gray-200">{uc.category}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Business Value Summary */}
        <div className="px-12 py-8 border-b border-gray-200">
          <div className="flex items-center gap-2 mb-4">
            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-600 text-white text-xs font-bold">3</span>
            <h2 className="text-lg font-bold text-gray-900">Estimated Business Value</h2>
          </div>

          {/* Total value hero */}
          <div className="rounded-xl bg-blue-50 border border-blue-200 p-6 text-center mb-6">
            <p className="text-xs text-blue-600 uppercase tracking-wide font-medium">Total Estimated Annual Value</p>
            <p className="text-4xl font-bold text-gray-900 mt-2">{formatCurrencyShort(totalAnnualValue)}</p>
            <p className="text-sm text-gray-500 mt-1">labor value recaptured per year across selected use cases</p>
            <div className="grid grid-cols-3 gap-4 mt-4 max-w-md mx-auto">
              <div>
                <p className="text-xl font-bold text-gray-900">{totalFTEs.toFixed(1)}</p>
                <p className="text-[10px] text-gray-500">FTE equivalent / mo</p>
              </div>
              <div>
                <p className="text-xl font-bold text-gray-900">{totalHours.toLocaleString()}</p>
                <p className="text-[10px] text-gray-500">hours saved / mo</p>
              </div>
              <div>
                <p className="text-xl font-bold text-gray-900">+{Math.round((totalHours / 160) * 12)}%</p>
                <p className="text-[10px] text-gray-500">capacity unlocked</p>
              </div>
            </div>
          </div>

          {/* Per use case breakdown */}
          <div className="space-y-3">
            {valueCards.map((card) => (
              <div key={card.useCase.id} className="rounded-lg border border-gray-100 p-4">
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span className="text-lg">{card.useCase.icon}</span>
                    <div>
                      <p className="text-sm font-semibold text-gray-900">{card.useCase.label}</p>
                      <p className="text-xs text-gray-500">{card.useCase.hook}</p>
                    </div>
                  </div>
                  <span className="text-sm font-bold text-blue-600">{formatCurrencyShort(card.estimatedLaborValueRecaptured)}/yr</span>
                </div>
                <div className="grid grid-cols-3 gap-3 mt-2 pt-2 border-t border-gray-100">
                  <div className="text-center">
                    <p className="text-sm font-bold text-gray-900">{card.estimatedFTESaved.toFixed(1)} FTE</p>
                    <p className="text-[10px] text-gray-400">equivalent</p>
                  </div>
                  <div className="text-center">
                    <p className="text-sm font-bold text-gray-900">{card.cycleTimeLabel}</p>
                    <p className="text-[10px] text-gray-400">cycle time</p>
                  </div>
                  <div className="text-center">
                    <p className="text-sm font-bold text-gray-900">{card.errorReductionLabel}</p>
                    <p className="text-[10px] text-gray-400">error rate</p>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Value assumptions */}
          <div className="mt-4 p-3 rounded-lg bg-gray-50 border border-gray-100">
            <p className="text-xs font-medium text-gray-500 mb-1">Value Assumptions Used</p>
            <p className="text-xs text-gray-400">
              Avg. fully-loaded FTE cost: {formatCurrencyShort(discovery.avgFTECost)}/yr  ·{' '}
              Recoverable time: {discovery.fteRecoverablePct}%  ·{' '}
              Segment scalar: {discovery.segment === 'enterprise' ? '1.5x' : discovery.segment === 'smc' ? '1.0x' : '0.5x'}
            </p>
          </div>
        </div>

        {/* Page break before investment section */}
        <div className="hidden print:block" style={{ pageBreakBefore: 'always' }} />

        {/* Investment Model */}
        <div className="px-12 py-8 border-b border-gray-200">
          <div className="flex items-center gap-2 mb-2">
            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-600 text-white text-xs font-bold">4</span>
            <h2 className="text-lg font-bold text-gray-900">Investment Model — Working Assumptions</h2>
          </div>
          <p className="text-xs text-gray-500 mb-4">These inputs were pre-populated based on the selected use case and segment, then can be adjusted by the seller during the consultation.</p>

          <div className="grid grid-cols-2 gap-4">
            <div className="rounded-lg border border-gray-100 p-4">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Copilot Usage</p>
              <div className="space-y-1 text-sm">
                <p className="flex justify-between"><span className="text-gray-500">Active Users</span><span className="font-medium text-gray-900">{inputs.activeUsers.toLocaleString()}</span></p>
                <p className="flex justify-between"><span className="text-gray-500">Queries / User / Month</span><span className="font-medium text-gray-900">{inputs.queriesPerUserPerMonth}</span></p>
                <p className="flex justify-between"><span className="text-gray-500">Est. Monthly Queries</span><span className="font-medium text-gray-900">{(inputs.activeUsers * inputs.queriesPerUserPerMonth).toLocaleString()}</span></p>
              </div>
            </div>
            <div className="rounded-lg border border-gray-100 p-4">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Azure Foundry</p>
              <div className="space-y-1 text-sm">
                <p className="flex justify-between"><span className="text-gray-500">PTU Hours / Month</span><span className="font-medium text-gray-900">{inputs.ptuHoursPerMonth}</span></p>
                <p className="flex justify-between"><span className="text-gray-500">Monthly Fabric Spend</span><span className="font-medium text-gray-900">${inputs.fabricMonthlySpend.toLocaleString()}</span></p>
              </div>
            </div>
            <div className="rounded-lg border border-gray-100 p-4">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">GitHub Copilot</p>
              <div className="space-y-1 text-sm">
                <p className="flex justify-between"><span className="text-gray-500">Seats</span><span className="font-medium text-gray-900">{inputs.githubCopilotSeats}</span></p>
                <p className="flex justify-between"><span className="text-gray-500">Price / Seat / Month</span><span className="font-medium text-gray-900">${inputs.githubCopilotPricePerSeat}</span></p>
              </div>
            </div>
            <div className="rounded-lg border border-gray-100 p-4">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Contract Context</p>
              <div className="space-y-1 text-sm">
                <p className="flex justify-between"><span className="text-gray-500">ACO Discount</span><span className="font-medium text-gray-900">{inputs.acoDiscountPct}%</span></p>
                <p className="flex justify-between"><span className="text-gray-500">Has MACC</span><span className="font-medium text-gray-900">{inputs.hasMACC ? 'Yes' : 'No'}</span></p>
                {inputs.hasMACC && <p className="flex justify-between"><span className="text-gray-500">MACC Burn %</span><span className="font-medium text-gray-900">{inputs.maccBurnPct}%</span></p>}
              </div>
            </div>
          </div>
        </div>

        {/* Listen & Consult Context */}
        <div className="px-12 py-8 border-b border-gray-200">
          <div className="flex items-center gap-2 mb-4">
            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-600 text-white text-xs font-bold">5</span>
            <h2 className="text-lg font-bold text-gray-900">Listen & Consult — Stage Context</h2>
          </div>
          <div className="space-y-3 text-xs text-gray-600 leading-relaxed">
            <p>
              This assessment was developed during the Listen & Consult stage of the Microsoft Customer Engagement Methodology (MCEM). At this stage, the Account Executive and Account Technology Strategist are building a deep understanding of the customer's strategic priorities, challenges, and desired outcomes — before recommending specific solutions.
            </p>
            <p>
              The figures in this document are directional estimates based on industry benchmarks and the customer profile selected. They are intended to anchor a value conversation, not to serve as a formal business case. All assumptions should be validated with the customer before advancing to the Inspire & Design stage.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-6 mt-6">
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Verifiable Outcomes for This Stage</p>
              <div className="space-y-1.5">
                {['Stakeholder identification complete', 'Customer needs and outcomes defined', 'Initial Solution Play selected', 'Customer priorities identified', 'Customer timeline and initial budget outlined'].map((item) => (
                  <div key={item} className="flex items-start gap-2 text-xs text-gray-600">
                    <span className="text-green-500 mt-0.5">✓</span>
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>
            <div>
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">Recommended Next Steps</p>
              <div className="space-y-1.5">
                {[
                  'Validate use case priorities with customer stakeholders',
                  'Identify technical decision makers and budget owners',
                  'Align on evaluation criteria and approval process',
                  'Schedule Inspire & Design workshop',
                  'Engage ATS and relevant Specialists',
                ].map((item) => (
                  <div key={item} className="flex items-start gap-2 text-xs text-gray-600">
                    <span className="text-blue-500 mt-0.5">→</span>
                    <span>{item}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* Notes section */}
        <div className="px-12 py-8 border-b border-gray-200">
          <div className="flex items-center gap-2 mb-4">
            <span className="flex items-center justify-center w-6 h-6 rounded-full bg-blue-600 text-white text-xs font-bold">6</span>
            <h2 className="text-lg font-bold text-gray-900">Notes & Customer Input</h2>
          </div>
          <div className="min-h-[200px] rounded-lg border-2 border-dashed border-gray-200 p-4">
            <p className="text-xs text-gray-300 italic">Space for handwritten or typed notes during the customer conversation...</p>
          </div>
        </div>

        {/* Footer */}
        <div className="px-12 py-6 flex items-center justify-between">
          <p className="text-[10px] text-gray-400">
            Microsoft Confidential — For internal seller use and customer-facing discussions only
          </p>
          <p className="text-[10px] text-gray-400">
            Azure AI Business Value Estimator · {today}
          </p>
        </div>
      </div>
    </div>
  );
}
